name: build and test

on:
  push:
  pull_request:
    paths:
      - "**.cs"
      - "**.csproj"

env:
  DOTNET_VERSION: "5.0.301" # The .NET SDK version to use

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        working-directory: ./Obligatorio/Ministerio de Turismo
        run: dotnet restore

      - name: Build
        working-directory: ./Obligatorio/Ministerio de Turismo
        run: dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: ./Obligatorio/Ministerio de Turismo
        run: dotnet test --no-restore --verbosity normal

      - name: Codecov
        uses: codecov/codecov-action@v1.5.2
