name: build and test

on:
  push:
  pull_request:
    paths:
      - "**.cs"
      - "**.csproj"

env:
  DOTNET_VERSION: "5.0.301" # The .NET SDK version to use

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.x

      - name: Install dependencies
        working-directory: ./Obligatorio/Ministerio de Turismo
        run: dotnet restore

      - name: Build
        working-directory: ./Obligatorio/Ministerio de Turismo
        run: dotnet build --no-restore

      - name: Test
        working-directory: ./Obligatorio/Ministerio de Turismo
        run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName\!~SpecChargingPoint.Features


      - name: Get a report
        uses: dorny/test-reporter@v1
        with:
          name: DotNET Tests Results
          path: '**/*.trx'
          reporter: dotnet-trx
          fail-on-error: 'false'
        
      - name: Upload tests results artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: GitHubActionsTestsResults
          path: '**/*.trx'
